In [2]:
from scipy.stats import norm

In [5]:
alpha = 1-0.997
norm.ppf(alpha/2)

-2.9677379253417833

In [7]:
p_placebo = 189./11034
p_aspirin = 104./11037
print p_placebo
print p_aspirin

0.0171288743883
0.00942285041225


In [60]:
a5 = p_placebo-p_aspirin
print a5

0.007706023976


In [26]:
import numpy as np

In [17]:
na = 11037
na_i = 104
data_a = np.concatenate([np.ones((na_i)), np.zeros((na-na_i))])

In [19]:
data_a.shape

(11037,)

In [20]:
from statsmodels.stats.weightstats import _zconfint_generic, _tconfint_generic

/home/ar600/anaconda2/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)


In [21]:
a6 = _tconfint_generic(data_a.mean(), data_a.std()/np.sqrt(len(data_a)), len(data_a) - 1, 0.05, 'two-sided')

In [22]:
print a6

(0.0076202249371126393, 0.01122547588738677)


In [31]:
import scipy
from statsmodels.stats.weightstats import *
from statsmodels.stats.proportion import proportion_confint

def proportions_confint_diff_ind(sample1, sample2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)   
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    
    return (left_boundary, right_boundary)

In [28]:
npc = 11034
npc_i = 189
data_p = np.concatenate([np.ones((np_i)), np.zeros((npc-np_i))])

In [29]:
data_p.shape

(11034,)

In [32]:
print "confidence interval: [%f, %f]" % proportions_confint_diff_ind(data_p, data_a)

confidence interval: [0.004688, 0.010724]


In [54]:
odds_p = p_placebo/(1-p_placebo)

In [55]:
odds_a = p_aspirin/(1-p_aspirin)

In [36]:
odds_p/odds_a

1.8320539419087138

In [37]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples

In [38]:
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

In [73]:
np.random.seed(0)
samples_a = get_bootstrap_samples(data_a,1000)
samples_p = get_bootstrap_samples(data_p,1000)

In [74]:
def get_odds(sample):
    return sum(sample)/(len(sample)-sum(sample))

In [75]:
odds_p = map(get_odds, samples_p)

In [76]:
odds_a = map(get_odds, samples_a)

In [77]:
odds = np.array(odds_p)/np.array(odds_a)
len(odds)

1000

In [78]:
a8 = _tconfint_generic(odds.mean(), odds.std()/np.sqrt(len(odds)), len(odds) - 1, 0.05, 'two-sided')
print a8

(1.833798702578872, 1.862909063196182)


In [70]:
len(odds_a)

1000

In [83]:
from scipy import stats
print "%.6f" % stats.binom_test(22, 50, 0.75, alternative = 'two-sided')

0.000003


In [84]:
import pandas as pd

trees=pd.read_csv('pines.txt',delimiter='\t')

In [85]:
trees.head()

sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4

In [91]:
ret = stats.binned_statistic_2d(trees.we, trees.sn,None,'count', bins=[5,5])
observed = ret.statistic

In [98]:
m = observed.mean()
print m
print observed

23.36
[[ 18.  14.  12.   8.   7.]
 [ 26.  12.  24.  19.   8.]
 [ 29.  22.  15.  31.  37.]
 [ 25.  34.  50.  50.  27.]
 [ 20.  25.  37.   7.  27.]]


In [94]:
expected = m*np.ones((5,5))
expected

array([[ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36],
       [ 23.36,  23.36,  23.36,  23.36,  23.36]])

In [106]:
stats.chisquare(observed.reshape(25), expected.reshape(25), ddof = 0)

Power_divergenceResult(statistic=150.58904109589042, pvalue=2.5746697749672791e-20)

In [105]:
expected.reshape(25)

array([ 23.36,  23.36,  23.36,  23.36,  23.36,  23.36,  23.36,  23.36,
        23.36,  23.36,  23.36,  23.36,  23.36,  23.36,  23.36,  23.36,
        23.36,  23.36,  23.36,  23.36,  23.36,  23.36,  23.36,  23.36,
        23.36])